version: '3.1'

services:
  agenda_pg:
    image: postgres:15.1
    container_name: agenda_pg
    restart: always
    environment:
      POSTGRES_DB: agendadb
      POSTGRES_USER: uagenda
      POSTGRES_PASSWORD: pagenda1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432